src/main/java/com/desafio_tecnico/model/CiadadePdf.java
package com.desafio_tecnico.model;

public class CiadadePdf {
	
	private String nome;
	
	private String populacao;
	
	private String nomeEstado;

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getPopulacao() {
		return populacao;
	}

	public void setPopulacao(String populacao) {
		this.populacao = populacao;
	}

	public String getNomeEstado() {
		return nomeEstado;
	}

	public void setNomeEstado(String nomeEstado) {
		this.nomeEstado = nomeEstado;
	}
	
}

src/main/java/com/desafio_tecnico/model/Cidade.java
package com.desafio_tecnico.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

@Entity
@Table(name = "cidade", uniqueConstraints = @UniqueConstraint(columnNames={"estado_id", "nome"}))
public class Cidade implements Serializable {
	
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	
	@Column(nullable = false)
	private String nome;
	
	@Column(name = "quantidade_populacao", nullable = false)
	private Long quantidadePopulacao;
	
	@ManyToOne
	@JoinColumn(name = "estado_id", nullable = false)
	private Estado estado;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Long getQuantidadePopulacao() {
		return quantidadePopulacao;
	}

	public void setQuantidadePopulacao(Long quantidadePopulacao) {
		this.quantidadePopulacao = quantidadePopulacao;
	}

	public Estado getEstado() {
		return estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Cidade other = (Cidade) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Cidade [id=" + id + "]";
	}

}

src/main/java/com/desafio_tecnico/model/Estado.java
package com.desafio_tecnico.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

@Entity()
@Table(name = "estado")
public class Estado implements Serializable {

	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	
	private String nome;
	
	@OneToMany(mappedBy = "estado", fetch = FetchType.LAZY)
	private List<Cidade> cidades;
	
	private String sigla;
	
	@Transient
	private Integer populacao;
	
	@Transient
	private BigDecimal valorPopulacao;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public List<Cidade> getCidades() {
		return cidades;
	}

	public void setCidades(List<Cidade> cidades) {
		this.cidades = cidades;
	}

	public String getSigla() {
		return sigla;
	}

	public void setSigla(String sigla) {
		this.sigla = sigla;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Estado other = (Estado) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Estado [id=" + id + "]";
	}

	public Integer getPopulacao() {
		return populacao;
	}

	public void setPopulacao(Integer populacao) {
		this.populacao = populacao;
	}

	public BigDecimal getValorPopulacao() {
		return valorPopulacao;
	}

	public void setValorPopulacao(BigDecimal valorPopulacao) {
		this.valorPopulacao = valorPopulacao;
	}

}

src/main/java/com/desafio_tecnico/controller/CidadeController.java
package com.desafio_tecnico.controller;

import java.io.IOException;
import java.io.Serializable;
import java.util.List;

import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.event.AjaxBehaviorEvent;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.apache.commons.lang3.StringUtils;
import org.primefaces.model.UploadedFile;

import com.desafio_tecnico.converter.EstadoConverter;
import com.desafio_tecnico.exception.CidadeParaEstadoJaExistenteException;
import com.desafio_tecnico.exception.ExclusaoCidadeRsException;
import com.desafio_tecnico.model.Cidade;
import com.desafio_tecnico.model.Estado;
import com.desafio_tecnico.service.CidadeService;
import com.desafio_tecnico.service.EstadoService;
import com.desafio_tecnico.util.Constants;
import com.desafio_tecnico.util.FacesMessages;

@Named
@ViewScoped
public class CidadeController implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	@Inject
	private CidadeService cidadeService;
	
	@Inject
	private EstadoService estadoService;
	
    @Inject
    private FacesMessages messages;
	
	private Cidade cidadeSelecionada;
	
	private List<Estado> estados;
	
	private List<Cidade> cidades;
	
	private Estado estadoSelecionado;
	
	private Converter estadoConverter;
	
	private Cidade novaCidade;
	
	private UploadedFile file;
	
	public void init() throws CidadeParaEstadoJaExistenteException {
		this.estadoSelecionado = this.estadoService.buscarPorSigla("SC");
		this.estados = this.estadoService.buscarTodosEstados();
		this.cidades = this.cidadeService.buscarPorEstado(estadoSelecionado);
		estadoConverter = new EstadoConverter(estados);
	}
	
	public void initNovaCidade() {
		novaCidade = new Cidade();
		novaCidade.setEstado(this.estadoService.buscarPorSigla("SC"));
		this.estados = this.estadoService.buscarTodosEstados();
		estadoConverter = new EstadoConverter(estados);
	}
	
    public void uploadCidadesEmLote() throws IOException {
    	if (file == null) {
    		messages.info("Você precisa selecionar um arquivo primeiro!");	
    	} else {
    		try {
        		this.cidadeService.inserirArquivosEmLote(file);
        		messages.info("Cidades inseridas com sucesso!");
    		} catch (CidadeParaEstadoJaExistenteException e) {
    			messages.info("O arquivos possui 1 ou mais cidades já cadastradas!");
    		}
    	}
    }
	
	public void salvar() throws IOException {
		try {
			this.cidadeService.salvar(novaCidade);
			FacesContext.getCurrentInstance().getExternalContext().redirect(Constants.PAGINA_LISTAGEM_CIDADES);
		} catch (CidadeParaEstadoJaExistenteException e) {
			messages.info(e.getMessage());
		}
	}
	
	public void excluir() {
		try {
			this.cidadeService.excluir(cidadeSelecionada);
		} catch(ExclusaoCidadeRsException e) {
			messages.info(e.getMessage());
		}
		
		this.cidadeSelecionada = null;
		this.cidades = this.cidadeService.buscarPorEstado(estadoSelecionado);
	}
	
	public void atualizarCidadePorEstadoSelecionado(final AjaxBehaviorEvent event) {
		this.cidades = this.cidadeService.buscarPorEstado(estadoSelecionado);
	}
	
	public void redirectToListagemEstados() throws IOException  {
		FacesContext.getCurrentInstance().getExternalContext().redirect(Constants.PAGINA_LISTAGEM_ESTADOS);
	}
	
	public void redirectToInsercaoCidade() throws IOException {
		FacesContext.getCurrentInstance().getExternalContext().redirect(Constants.PAGINA_NOVA_CIDADE);
	}
	
	public void redirectToImportarCidadesEmLote() throws IOException {
		FacesContext.getCurrentInstance().getExternalContext().redirect(Constants.PAGINA_IMPORTAR_CIDADES_EM_LOTE);
	}
	
    public boolean isCidadeSelecionadaDisponivel() {
        return cidadeSelecionada != null && cidadeSelecionada.getId() != null;
    }
	
	public Cidade getCidadeSelecionada() {
		return cidadeSelecionada;
	}

	public void setCidadeSelecionada(Cidade cidadeSelecionada) {
		this.cidadeSelecionada = cidadeSelecionada;
	}

	public List<Estado> getEstados() {
		return estados;
	}

	public void setEstados(List<Estado> estados) {
		this.estados = estados;
	}

	public Estado getEstadoSelecionado() {
		return estadoSelecionado;
	}

	public void setEstadoSelecionado(Estado estadoSelecionado) {
		this.estadoSelecionado = estadoSelecionado;
	}

	public List<Cidade> getCidades() {
		return cidades;
	}

	public void setCidades(List<Cidade> cidades) {
		this.cidades = cidades;
	}

	public Cidade getNovaCidade() {
		return novaCidade;
	}

	public void setNovaCidade(Cidade novaCidade) {
		this.novaCidade = novaCidade;
	}

	public Converter getEstadoConverter() {
		return estadoConverter;
	}
	
    public UploadedFile getFile() {
        return file;
    }
 
    public void setFile(UploadedFile file) {
        this.file = file;
    }

}

src/main/java/com/desafio_tecnico/controller/EstadoController.java
package com.desafio_tecnico.controller;

import java.io.IOException;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;

import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.desafio_tecnico.converter.EstadoConverter;
import com.desafio_tecnico.model.Estado;
import com.desafio_tecnico.service.EstadoService;
import com.desafio_tecnico.util.Constants;

@Named
@ViewScoped
public class EstadoController implements Serializable  {
	
	private static final long serialVersionUID = 1L;
	
	@Inject
	private EstadoService estadoService;
	
	private Estado estadoSelecionado;
	
	private List<Estado> estados;
	
	private Converter estadoConverter;
	
	public void init() {
		this.estados = this.estadoService.buscarTodosEstados();
		estadoConverter = new EstadoConverter(estados);
		setUpEstados();
	}
	
	public void setUpEstados() {
		for(Estado estado : estados) {
			estado.setPopulacao(estadoService.buscarPopulacao(estado));
			estado.setValorPopulacao(estadoService.calcularCustoEstado(estado));
		}
	}
	
	public void redirectToListagemCidades() throws IOException {
		FacesContext.getCurrentInstance().getExternalContext().redirect(Constants.PAGINA_LISTAGEM_CIDADES);
	}

	public Estado getEstadoSelecionado() {
		return estadoSelecionado;
	}

	public void setEstadoSelecionado(Estado estadoSelecionado) {
		this.estadoSelecionado = estadoSelecionado;
	}
	
	public BigDecimal getCustoEstado() {
		if (this.estadoSelecionado.getId() == null) {
			return null;
		}
		return this.estadoService.calcularCustoEstado(this.estadoSelecionado);
	}
	
	public void selecionarEstado(Estado estado) {
		this.estadoSelecionado = estado;
	}
	
	public Converter getEstadoConverter() {
		return estadoConverter;
	}

	public List<Estado> getEstados() {
		return estados;
	}

	public void setEstados(List<Estado> estados) {
		this.estados = estados;
	}
	
}

src/main/webapp/cidades.xhtml
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
 	xmlns:h="http://xmlns.jcp.org/jsf/html"
 	xmlns:f="http://xmlns.jcp.org/jsf/core"
 	xmlns:p="http://primefaces.org/ui"
 	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
 	template="WEB-INF/template/Layout.xhtml">
 	
<ui:define name="titulo">
	<p:outputLabel id="tituloPagina" value="#{labels['cidades.title']}"/>
</ui:define>

<ui:define name="conteudo">
	<f:metadata>
		<f:viewAction action="#{cidadeController.init}" />
	</f:metadata>
	
	<h:form id="frm">
		<p:messages id="messages" />
	
		<p:toolbar id="toolbar">
			<f:facet name="left">
				
				<p:graphicImage id="imgBandeira" value="resources/desafio_tecnico/bandeira#{cidadeController.estadoSelecionado.sigla}.jpg" />
				
				<span id="separadorBandeira" class="ui-separator">
	                <span class="ui-icon ui-icon-grip-dotted-vertical" />
	            </span>
				
		        <p:selectOneMenu id="estado" name="estado" value="#{cidadeController.estadoSelecionado}" converter="#{cidadeController.estadoConverter}">
		        	<p:ajax event="itemSelect" update="cidadesDataTable imgBandeira" listener="#{cidadeController.atualizarCidadePorEstadoSelecionado}" />
		            <f:selectItems value="#{cidadeController.estados}" var="estado" itemValue="#{estado}" itemLabel="#{estado.nome}" />
		        </p:selectOneMenu>
		        
   				<span class="ui-separator">
	                <span class="ui-icon ui-icon-grip-dotted-vertical" />
	            </span>
	            
	            <p:commandButton value="#{labels['cidades.btn.add-city']}" icon="fa fa-plus" action="#{cidadeController.redirectToInsercaoCidade}" />
		        
		        <span class="ui-separator">
	                <span class="ui-icon ui-icon-grip-dotted-vertical" />
	            </span>
	            
	            <p:commandButton title="Excluir" icon="fa fa-trash" 
	            	disabled="#{not cidadeController.cidadeSelecionadaDisponivel}"
	            	actionListener="#{cidadeController.excluir}"
	            	update="messages cidadesDataTable toolbar"
	            	process="@this">
	            	<p:confirm icon="ui-icon-alert" header="Confirmação de exclusão" 
	            		message="#{labels['cidades.exclude-city']}" />	
            	</p:commandButton>
            	
            	<span class="ui-separator">
	                <span class="ui-icon ui-icon-grip-dotted-vertical" />
	            </span>
		        
		        <p:commandButton title="#{labels['cidades.btn.import-cities']}" icon="fa fa-file-excel-o" action="#{cidadeController.redirectToImportarCidadesEmLote}" />
	            
			</f:facet>
		</p:toolbar>
		
		<p:spacer height="20px" />
		
		<p:dataTable id="cidadesDataTable" value="#{cidadeController.cidades}"
			var="cidade" emptyMessage="#{labels['cidades.data-table.empty']}"
			paginator="true" rows="3" paginatorPosition="bottom"
			selectionMode="single" selection="#{cidadeController.cidadeSelecionada}" rowKey="#{cidade.id}">
			
			<p:ajax event="rowSelect" update="frm:toolbar" />
			<p:ajax event="rowUnselect" update="frm:toolbar" />
			
			<p:column headerText="#{labels['cidades.data-table.column.id']}">
				<h:outputText value="#{cidade.id}"></h:outputText>
			</p:column>
			
			<p:column headerText="#{labels['cidades.data-table.column.name']}">
				<h:outputText value="#{cidade.nome}"></h:outputText>
			</p:column>
			
			<p:column headerText="#{labels['cidades.data-table.column.state']}">
				<h:outputText value="#{cidade.estado.nome}"></h:outputText>
			</p:column>
			
			<p:column headerText="#{labels['cidades.data-table.column.population']}">
				<h:outputText value="#{cidade.quantidadePopulacao}"></h:outputText>
			</p:column>
			
		</p:dataTable>
		
	</h:form>
</ui:define>

</ui:composition>

src/main/webapp/estados.xhtml
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
 	xmlns:h="http://xmlns.jcp.org/jsf/html"
 	xmlns:f="http://xmlns.jcp.org/jsf/core"
 	xmlns:p="http://primefaces.org/ui"
 	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
 	template="WEB-INF/template/Layout.xhtml">
 	
<ui:define name="titulo">
	<p:outputLabel id="tituloPagina" value="#{labels['estados.title']}"/>
</ui:define>

<ui:define name="conteudo">
	<f:metadata>
		<f:viewAction action="#{estadoController.init}" />
	</f:metadata>
	
	<h:form id="frmEstado">
		<p:messages id="messages" />
		
		<p:dataTable id="estadosDataTable" value="#{estadoController.estados}"
						var="estado" emptyMessage="#{labels['estados.data-table.empty']}">
			
			<p:column headerText="#{labels['estados.data-table.column.name']}">
				<h:outputText value="#{estado.nome}"></h:outputText>
			</p:column>
			
			<p:column headerText="#{labels['estados.data-table.column.population']}">
				<h:outputText value="#{estado.populacao}"></h:outputText>
			</p:column>
			
			<p:column headerText="#{labels['estados.data-table.column.population-cost']}">
				<h:outputText value="#{estado.valorPopulacao}">
			        <f:convertNumber type="number" locale="#{labels['estados.locale.pt-br']}"/>
				</h:outputText>
			</p:column>
			
		</p:dataTable>
		
	</h:form>
</ui:define>

</ui:composition>

src/main/webapp/importarCidadesEmLote.xhtml
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
 	xmlns:h="http://xmlns.jcp.org/jsf/html"
 	xmlns:f="http://xmlns.jcp.org/jsf/core"
 	xmlns:p="http://primefaces.org/ui"
 	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
 	template="WEB-INF/template/Layout.xhtml">
 	
<ui:define name="titulo">
	<p:outputLabel id="tituloPagina" value="#{labels['importar.title']}"/>
</ui:define>

<ui:define name="conteudo">

	<h:form id="frmImportar" enctype="multipart/form-data">
		<p:messages id="messages" />

		<h:panelGrid id="cidadePanelGrid" columns="2">
			<p:outputLabel value="#{labels['importar.select-document']}" for="btnImportar" />
			<p:fileUpload id="btnImportar" value="#{cidadeController.file}" mode="simple" skinSimple="true"/>
		    <br />
		    <p:commandButton value="#{labels['importar.import']}" ajax="false" action="#{cidadeController.uploadCidadesEmLote}" update="messages" />
		</h:panelGrid>
	</h:form>

</ui:define>

</ui:composition>

src/main/webapp/novaCidade.xhtml
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
 	xmlns:h="http://xmlns.jcp.org/jsf/html"
 	xmlns:f="http://xmlns.jcp.org/jsf/core"
 	xmlns:p="http://primefaces.org/ui"
 	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
 	template="WEB-INF/template/Layout.xhtml">
 	
<ui:define name="titulo">
	<p:outputLabel id="tituloPagina" value="#{labels['importar.title']}"/>
</ui:define>

<ui:define name="conteudo">

	<f:metadata>
		<f:viewAction action="#{cidadeController.initNovaCidade}" />
	</f:metadata>

	<h:form id="frmNovoUsuario">
		<p:messages id="messages" />

		<h:panelGrid id="cidadePanelGrid" columns="2">
			<p:outputLabel value="#{labels['novaCidade.form.field.name']}:" for="nome" />
			<p:inputText id="nome" size="80" maxlength="120" required="true"
				value="#{cidadeController.novaCidade.nome}" />
			
			<p:outputLabel value="#{labels['novaCidade.form.field.state']}:" for="estadoSelect" />	
	        <p:selectOneMenu id="estadoSelect" value="#{cidadeController.novaCidade.estado}" 
			        					style="width:450px" converter="#{cidadeController.estadoConverter}">
	            <f:selectItems value="#{cidadeController.estados}" var="estado" itemValue="#{estado}" itemLabel="#{estado.nome}" />
	        </p:selectOneMenu>
			
			<p:outputLabel value="#{labels['novaCidade.form.field.population']}:" for="populacao" />
			<p:inputText id="populacao" size="80" maxlength="20" required="true"
				value="#{cidadeController.novaCidade.quantidadePopulacao}"/>
				
			<p:commandButton id="salvarCommandButton" value="#{labels['novaCidade.form.btn.save']}" update="messages"
								actionListener="#{cidadeController.salvar}" />
		</h:panelGrid>
	</h:form>

</ui:define>

</ui:composition>